
import ReactQueryProvider from '@/features/ReactQueryProvider'
import { ReduxProvider } from '@/features/ReduxProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import MenuComponents from './components/MenuComponents'
import './globals.css'
import { store } from './store' 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <ReduxProvider>
        <ReactQueryProvider>

      
      <body className="flex flex-col">
       
        <nav className='w-full bg-gradient-to-r
         to-[#3195b9] via-[#2ba8a6] from-[#16879ba7] h-12'>
            
            </nav>
         <section className='flex  w-screen h-screen relative'>
         
          <section className={``}>
          <MenuComponents/>
          </section>

          <section className='w-full bg-slate-200 flex flex-col h-full'>
            
          {children}
          </section>
       
        </section>
       
        </body>
        </ReactQueryProvider>
      </ReduxProvider>
    </html>
  )
}
