
import { ReduxProvider } from '@/features/ReduxProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'react-redux'
import MenuComponents from './components/MenuComponents'
import './globals.css'
import { store } from './store' 

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
         <section className='flex  w-screen h-screen relative'>
          <section className={``}>
          <MenuComponents/>
          </section>

          <section className='w-full bg-slate-400 flex flex-col'>
          {children}
          </section>
       
        </section>
        </ReduxProvider>
        </body>
    </html>
  )
}
